sql_conn_pool_test:sql_conn_pool_test.cpp sql_conn_pool.cpp sql_conn_pool.h /home/wt/Project/my_Server/log/log.h /home/wt/Project/my_Server/log/log.cpp
	g++ -std=c++14 -O2 -Wall -g sql_conn_pool_test.cpp sql_conn_pool.cpp sql_conn_pool.h /home/wt/Project/my_Server/log/log.h /home/wt/Project/my_Server/log/log.cpp -o sql_conn_pool_test -lpthread -L/usr/lib64/mysql -lmysqlclient
